---
title: "R Notebook"
output: html_notebook
---

```{r}
library(RColorBrewer)
```

```{r}
data = read.csv("datos/HTRU_2.csv",header=F,sep =",")
attach(data)
```

```{r}
namelist <- c('Mean of the integrated profile','Standard deviation of the integrated profile', 'Excess kurtosis of the integrated profile','Skewness of the integrated profile','Mean of the DM-SNR curve','Standard deviation of the DM-SNR curve','Excess kurtosis of the DM-SNR curve',
'Skewness of the DM-SNR curve','class')

colnames(data) <- namelist
```

```{r}
dim(data)
```

```{r}
names(data)
```

```{r}
str(data)
```


```{r}
normalize <- function(x) {
  return ((x-min(x))/(max(x)-min(x)))
}
```


```{r}
data_n <- as.data.frame(lapply(data[c(1:ncol(data)-1)], normalize))
data_n$V9 <- data$V9
str(data_n)
```

```{r}
m = as.matrix(data_n[1:ncol(data_n)-1])

cols  <- colorRampPalette(brewer.pal(12, "Set3"), alpha=TRUE)(ncol(m))
colsm <-matrix(rep(cols, each=nrow(m)), ncol=ncol(m))

boxplot(m~col(m), horizontal=TRUE, outline=TRUE, lty=1, staplewex=0, boxwex=0.8, boxlwd=1, medlwd=1, col=cols, xaxt="n", yaxt="n")

# add axes and title
axis(side=1, at=seq(0,100,by=10), cex.axis=0.8, lty=0, tick=NA, line=-1)
axis(side=1, at=50, labels="Assigned Probability %", lty=0, tick=NA)
axis(side=2, at=1:8, cex.axis=0.8, lty=0, tick=NA, labels=colnames(m), las=2)
axis(side=2, at=17/2, labels="Phrase", lty=0, tick=NA, las=3, line=6)
title("Perceptions of Probability")
```

```{r}
removeOutliers <- function(data,n=3){
  f <- !logical(length = nrow(data))
  for (c in colnames(data)) {
    x <- data[[c]]
    g <- x > quantile(x,.25) - 0.5*n*IQR(x) & x < quantile(x,.75) + 0.5*n*IQR(x)
    f <- f & g
  }
  return(f)
}
```


```{r}
data_n <- subset(data_n,select=c("V1","V2","V3","V6","V7","V8","V9"))

filters = removeOutliers(data_n[1:ncol(data_n)-1],n=3)
data_clean <- subset(data_n,filters)
```


```{r}
m = as.matrix(data_clean[1:ncol(data_clean)-1])

cols  <- colorRampPalette(brewer.pal(12, "Set3"), alpha=TRUE)(ncol(m))
colsm <-matrix(rep(cols, each=nrow(m)), ncol=ncol(m))

boxplot(m~col(m), horizontal=TRUE, outline=TRUE, lty=1, staplewex=0, boxwex=0.8, boxlwd=1, medlwd=1, col=cols, xaxt="n", yaxt="n")

# add axes and title
axis(side=1, at=seq(0,100,by=10), cex.axis=0.8, lty=0, tick=NA, line=-1)
axis(side=1, at=50, labels="Assigned Probability %", lty=0, tick=NA)
axis(side=2, at=1:6, cex.axis=0.8, lty=0, tick=NA, labels=colnames(m), las=2)
axis(side=2, at=17/2, labels="Phrase", lty=0, tick=NA, las=3, line=6)
title("Perceptions of Probability")
```

```{r}
# Plot our dataset.
plot(data_clean[, 1:ncol(data_clean)-1], col = data_clean$V9, pch = 18, main = "Fisher's Wine Dataset")
```

```{r}
# Mclust comes with a method of hierarchical clustering. 
library(mclust)
# initialize 3 different classes.
initialk <- mclust::hc(data = data_clean, modelName = "EII")
initialk <- mclust::hclass(initialk,2)
```

```{r echo=TRUE}
mcl.model <- Mclust(data_clean[, 1:ncol(data_clean)-1], 2,verbose=FALSE)

plot(mcl.model, what = "classification", main = "Mclust Classification")
```


```{r echo=TRUE}
mcl.model$parameters$mean
```

```{r}
table(mcl.model$classification, data_clean$V9)
```
```
```{r}
set.seed(20)
DataCluster <- kmeans(data_clean[, 1:ncol(data_clean)-1], 2, nstart = 20)
DataCluster
```


```{r}
```


```{r}
table(DataCluster$cluster, data_clean$V9)
```

```{r echo=TRUE}
set.seed(20)
DataCluster <- kmeans(data_clean[, 1:ncol(data_clean)-1], 3, nstart = 20)
DataCluster
```